
version: 2

sources:
    - name: staging
      database: de-zoomcamp-375510
      schema: tripdata
      description: "staging"
      tables:
        - name: green_tripdata
        - name: yellow_tripdata
